### ISSUE TITLE
add codecov to repo

### ISSUE THREAD

**Issue by rodrigondec** [imobanco/py-bdd-context#18]
# Resume

Codecov is a great tool to have on our lib.

# Tasks
- [ ] install coverage lib (coverage = {extras = ["toml"], version = "^5.5"})
- [ ] create coverage command on makefile
- [ ] config coverage omit folders on pyproject.toml
- [ ] use coverage and upload it on test CI
